title: Ingab Kang
logo: /assets/img/selfie_cropped.jpg
description: PhD student @University of Michigan
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
cv: homepage/assets/cv_igkang.pdf
gs: https://scholar.google.com/citations?user=ik1D_PUAAAAJ&hl=en
email: mailto:igkang@umich.edu

